[package]
name = "enquire"
version = "0.0.2"
entrypoint = "main.typ"
categories = [ ]
disciplines = [ ]
compiler = "0.14.0"
description = "Utilities for creating questions in worksheets, exam papers or slides"

[template]
path = "package-default"
entrypoint = "main.typ"
