#let _marks-style = state("marks-style", "[1 mark(s)]")
#let _marks-weight = state("marks-weight", "bold")
#let _marks-formatter = state("marks-formatter", none)
#let _marks-inline = state("marks-inline", false)
#let _marks-total = state("total-marks")
